<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>KEBS | HOME</title>
        
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <link href="css/kebscss.css" rel="stylesheet" type="text/css" />
               
               	<!-- CuFon: Enables smooth pretty custom font rendering. 100% SEO friendly. To disable, remove this section -->
        <script type="text/javascript" src="js/cufon-yui.js"></script>
        <script type="text/javascript" src="js/arial.js"></script>
        <script type="text/javascript" src="js/cuf_run.js"></script>
        	<!-- CuFon ends -->
	<script type="text/javascript" src="js/jquery.js"></script>
	<script src="Scripts/swfobject_modified.js" type="text/javascript"></script>
	<script type="text/javascript" src="jquery.js"></script>
	
	<script type="text/javascript">
	$(document).ready(function() {
			$('.myMenu > li').bind('mouseover', openSubMenu);
			$('.myMenu > li').bind('mouseout', closeSubMenu);
			
			function openSubMenu() {
				$(this).find('ul').css('visibility', 'visible');	
			};
			
			function closeSubMenu() {
				$(this).find('ul').css('visibility', 'hidden');	
			};
					   
	});
	</script>

    </head>
    <body>

 	<div  class="header">
  		<table  bgcolor="#0066CC" width="100%"> <th><tr></tr></th></table>
	</div >

                     	 <div id="top-bar"> 
                                <div id="topbar-inner" style=" float:right; margin-right:180px ; font-size:12px; font-family:'Arial' ; color:#FFFFFF; f" >
                                  <p><a href="index.php" > Home  |</a>
                                    <a href="http://10.10.1.239/owa" target="_blank"> Staff Email  |</a> 
                                    <a href="#"> Contact KEBS </a>
                                  </p>
                                </div>
			</div>
			
 <div  class="header"> </br></div>
   <div class="header_resize">
    	  <div class="clr"> </div>          
       	 		  <div>
          			<div  style=" margin-top:0px"class="logo"><a href="index.php"><img src="images/keblogo.gif" width="411"  height="59"/></a> 
          			</br>
           		
                			<div  style=" float:right; margin-right:10px ; margin-bottom:10px; ">
                       
                       				<a href="http://onlinecatalogue.kebs.org" target="_blank">
                            			<img src="images/std_catalogue.png" border="0" align="absmiddle"  width="30" height="30"/> Library Catalogue |
                              			 </a>
                               
		              			<a href="http://sampleresult.kebs.org" target="_blank">
	                            		<img src="images/sample_results_2.png" border="0" align="absmiddle"  width="40" height="40"/> Sample Results Point |
	                            		 </a>      
	                                 
						<a href="http://webstore.kebs.org" target="_blank">
	                            		<img src="images/webstore.png" border="0" align="absmiddle"  width="40" height="40" />  Online Webstore |
	                                 	</a>
	                             
	                            		 <img src="images/phone.png" border="0" align="absmiddle"  width="25" height="25"/>
                             			<sup style=" background-color:#0066CC; color:#FFFFFF">free</sup> <b style="color:#0066cc">+254 782 23 44 33 </b>
                       			</div>

 				</div>
         		</div> 
            <div class="clr"></div>
            	
	
	
            <!-- <div>
			
               
                <ul id="nav" >
                    <li class="active"><a href="index.php?opt=home"><span>Home</span></a></li>
                    <li><a href="index.php?opt=about"><span>About KEBS</span></a> </li>
                     
                    <li><a href="index.php?opt=standards"><span>Standards</span></a></li>
                    <li><a href="index.php?opt=metrology"><span>Metrology </span></a></li>
                    <li><a href="index.php?opt=qai"><span>Quality Assurance & Inspection</span></a></li>
                    <li><a href="index.php?opt=testing"><span>Testing</span></a></li>
                    <li><a href="index.php?opt=certification"><span>Certification</span></a></li>
                    <li><a href="index.php?opt=nqi"><span>NQI Training </span></a></li>
                </ul>

            </div> -->
            				<div class="clr"></div>
              					<div class=" myMenu">
                         			 <ul id="nav" class="myMenu" >
                                                       <li class="active"><a href="index.php"><span>Home</span></a></li>
													    <li><a href="index.php?opt=about"><span>About Us</span></a></li>  
                                                    		<li><a href="index.php?opt=standards"><span>Standards</span></a> 
                                                            	   	<ul>
                                                                          <li><a href="#">sub menu item 1 </a></li>
                                                                          <li><a href="#">sub menu item 2</a></li>
                                                                          <li><a href="#">sub menu item 3</a></li>
                                                                          <li><a href="#">sub menu item 4</a></li>
                                                                         </ul>
                                                               </li>  
                                                                       
                                                               <li><a href="index.php?opt=metrology"><span>Metrology </span></a>
                                                               		<ul>
                                                                          <li><a href="#">sub menu item 1 </a></li>
                                                                          <li><a href="#">sub menu item 2</a></li>
                                                                          <li><a href="#">sub menu item 3</a></li>
                                                                          <li><a href="#">sub menu item 4</a></li>
                                                                         </ul>
                                                               </li>
                                                               
                                                               <li><a href="index.php?opt=qai"><span>Quality Assuarance & Inspection</span></a>
                                                               		<ul>
                                                                          <li><a href="#">sub menu item 1 </a></li>
                                                                          <li><a href="#">sub menu item 2</a></li>
                                                                          <li><a href="#">sub menu item 3</a></li>
                                                                          <li><a href="#">sub menu item 4</a></li>
                                                                         </ul>
                                                               </li>
                                                               
                                                               <li><a href="index.php?opt=testing"><span>Testing</span></a>
                                                               		<ul>
                                                                          <li><a href="#">sub menu item 1 </a></li>
                                                                          <li><a href="#">sub menu item 2</a></li>
                                                                          <li><a href="#">sub menu item 3</a></li>
                                                                          <li><a href="#">sub menu item 4</a></li>
                                                                         </ul>
                                                               </li>
                                                               
                                                               <li><a href="index.php?opt=certification"><span>Certification Body</span></a>
                                                               		<ul>
                                                                          <li><a href="#">sub menu item 1 </a></li>
                                                                          <li><a href="#">sub menu item 2</a></li>
                                                                          <li><a href="#">sub menu item 3</a></li>
                                                                          <li><a href="#">sub menu item 4</a></li>
                                                                         </ul>
                                                               </li>
                                                               
                                                               <li><a href="index.php?opt=nqi"><span>NQI Training </span></a>
                                                               		<ul>
                                                                          <li><a href="#">sub menu item 1 </a></li>
                                                                          <li><a href="#">sub menu item 2</a></li>
                                                                          <li><a href="#">sub menu item 3</a></li>
                                                                          <li><a href="#">sub menu item 4</a></li>
                                                                         </ul>
                                                               </li>  
                                                               
                                                                                       		                                                        
                                                                                       		
                                                                  
                                                                                                                                 
                                                            </ul>
                                         	 </div>

        </div>
        <?
            include_once 'includes/configdb.php';
    //include_once 'includes/db_connect.php';
        ?>