<html xmlns="http://www.w3.org/1999/xhtml">
<head>
        <title>KEBS - Standards, Training, Testing and Certification</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="css/style.css" rel="stylesheet" type="text/css" />
        <link href="css/kebs.css" rel="stylesheet" type="text/css" />

<!-- CuFon: Enables smooth pretty custom font rendering. 100% SEO friendly. To disable, remove this section -->
        <script type="text/javascript" src="js/cufon-yui.js"></script>
        <script type="text/javascript" src="js/arial.js"></script>
        <script type="text/javascript" src="js/cuf_run.js"></script>
<!-- CuFon ends -->

        <script type="text/javascript" src="js/jquery.js"></script>
        <script src="Scripts/swfobject_modified.js" type="text/javascript"></script>
        <script type="text/javascript" src="jquery.js"></script>
<!--    <script type="text/javascript" src="js/location2.js"></script> -->


	<!--    
	<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
        <script src="https://maps.googleapis.com/maps/api/js"></script>
        -->

<script type="text/javascript">
// Require https
if ($_SERVER['HTTPS'] != "on") {
    $url = "https://". $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];
    header("Location: $url");
    exit;
}
</script>

        <script type="text/javascript">
            $(document).ready(function() {
                $('.myMenu > li').bind('mouseover', openSubMenu);
                $('.myMenu > li').bind('mouseout', closeSubMenu);


                function openSubMenu() {
                    $(this).find('ul').css('visibility', 'visible');
                }
                ;

                function closeSubMenu() {
                    $(this).find('ul').css('visibility', 'hidden');
                }
                ;

            });
</script>
</head>
   
<body class ="body">
        <div  class="header"> </div>
        <div class="header_resize">
            <div class="clr"> </div>          
            	<div style="display:inline; float: left;">
            		<div class="logo"><a href="index.php"><img src="images/kebs_new_logo.png" /></a>
            		</div>
                </div>
            <div style="display: inline; float: right; height:59px; width:600px; alignment:right; padding-bottom: 2px">

<div style="height: 20px; text-align: right; font-size: 8pt; color: #ff0000; padding-top: -3px; font-weight: bold">

<span style="padding-right: 20px">
<a href="https://mail.kebs.org/owa" target="_blank">
<img src="images/email_logo.png" border="0" align="absmiddle"  height="25"/>
Staff Email</a>
</span>
|
<img src="images/toll-free.png" border="0" align="absmiddle"  width="25" height="25"/>
<span style=" background-color:#0066CC; color:#FFFFFF">
Toll Free
</span> 
<b style="color:#0066CC">0800221350 </b>
<!--
<span>|
<a href="index.php?opt=mpesa&view=mpesadetails" target="_blank">
<img src="images/mpesa_logo.png" border="0" align="absmiddle"  height="25"/>
PAY FOR KEBS GOODS OR SERVICES</a>
</span>
-->
</div><br>                
<!--
<div id="top-right" ><div style="display:inline; float:right; padding-right:10px; vertical-align:top"><a id="top-right" href="http://webstore.kebs.org/online-shop" target="_blank"><img src="images/webstore.png" border="0" align="absmiddle"  width="25" height="25"" />  Purchase Kenya Standards</a></div>
--> 

<div id="top-right" ><div style="display:inline; float:right; padding-right:10px; vertical-align:top">
    <a id="top-right" href="https://webstore.kebs.org" target="_blank"><img src="images/cart.png" border="0" align="absmiddle" width="20px" height="20px"/>&nbsp Buy Kenya Standards <img src="images/new_y.gif" /></a></div>
                       
<div style="display:inline; float:right; padding-right:10px; vertical-align:top; font-weight: normal;">
    <a id="top-right" href="https://www.kebs.org/sqmt/PSS/propose.html" target="_blank"><img src="images/catalogue.gif" border="0" align="absmiddle" /> Propose Standardization Requests</a>
</div>

<div style="display:inline; float:right; padding-right:10px; vertical-align:top; font-weight: normal;">
    <a id="top-right" href="http://onlinecatalogue.kebs.org/" target="_blank"><img src="images/catalogue.gif" border="0" align="absmiddle" /> Kenya Standards Catalogue </a>
</div>  

<div style="display:inline; float:right; padding-right:10px; vertical-align:top">
    <a id ="top-right" href="http://sampleresult.kebs.org" target="_blank"><img src="images/sample_results.png" border="0" align="absmiddle" /> Sample Test Results </a>
</div>
    </div>
</div>
            

           

 <div class="clr"></div>
            <hr style="color:#56b9f4; weight:1px;width: 100% "></hr>
            <div class="myMenu"> 
                <ul class="myMenu" id="navs" style="z-index: 1; position: relative">
                    <li class="active"><a href="index.php"><span>Home</span></a></li>
                    <li><a href="index.php?opt=aboutkebs"><span>About Us</span></a></li> 
                    
                    <li><a href="#"><span>Standards Development</span></a> 
                        <ul id="subnav" style="width: 175px">

                            <li><a href="index.php?opt=standards&view=standards">About our Standards</a></li>
                            <li><a href="index.php?opt=standards&view=standardstcs"> Technical committees</a></li>
                            <li><a href="index.php?opt=standards&view=kestandards">Standards Development</a></li>
                            <li><a href="#"> East African Standards</a></li>
<!--                            <li><a href="#"> Standards Levy</a></li>-->
                            <li><a href="index.php?opt=standards&view=wtonep"> WTO/TBT National enquiry point</a></li>
                            <li><a href="index.php?opt=standards&view=codex">National Executive Codex Committee</a></li>
                            <li><a href="index.php?opt=standards&view=biosafety">Biosafety</a></li>
                          <li><a href="index.php?opt=standards&view=faqstd"> FAQs(Standards)  </a></li>
                        </ul>
                    </li>  

                    <li><a href="#"><span>Metrology </span></a>
                        <ul id="subnav">
                            <li><a href="index.php?opt=metrology&view=about">About Metrology</a></li>
                            <li><a href="index.php?opt=metrology&view=why">Why KEBS Metrology</a></li>
                            <li><a href="index.php?opt=metrology&view=services"> Metrology Services</a></li>
                            <li><a href="index.php?opt=metrology&view=services"> Our laboratories</a></li>
                            <li> <a href="index.php?opt=metrology&view=training">Training for metrology </a> </li>
                            <li><a href="index.php?opt=metrology&view=accreditation">Accreditation </a></li>
                            <li><a href="index.php?opt=metrology&view=faq_met"> FAQs(Metrology)  </a></li>

                        </ul>
                    </li>

                    <li><a href="#"><span>Quality Assurance & Inspection</span></a>
                        <ul id="subnav" >
                            <li><a href="index.php?opt=qai&view=about">About Quality Assurance</a></li>
                        <li> <a href="index.php?opt=qai&view=marks">KEBS Marks of Quality <br>(SMark, DMark, ISM, Fortification)</a></li>
                       <li> <a href="index.php?opt=qai&view=pvoc">Import Inspection<br>(Goods & Motor Vehicles)</a></li>
                       <li>     <a href="?opt=qai&amp;view=new_pvoc_requirments">New PVoC Requirments</a></li> 
			<!-- 
			<li> <a href="index.php?opt=qai&view=functions">Functions</a></li>
                        <li> <a href="index.php?opt=qai&view=petroleum">Petroleum Standards</a></li> 
                        -->                        
                            <li><a href="index.php?opt=qai&view=pvoczones"> PVoC Zones of Responsibilities</a></li>
                            <li><a href="index.php?opt=qai&view=banned"> Banned Products</a></li>
                             <li><a href="index.php?opt=qai&view=faq_pvoc"> FAQs (PVoC)  </a></li>

                        </ul>
                    </li>

                 <li><a href="#"><span>Testing Services</span></a>
                        <ul>
                        <li><a href="index.php?opt=testing&view=about"> About testing</a></li>
                        <li><a href="index.php?opt=testing&view=services"> Testing Services</a></li>
                        <li><a href="index.php?opt=testing&view=ndt"> Non-Destructive testing</a></li>
                        <li><a href="index.php?opt=testing&view=analysis"> Testing Analysis</a></li>
                        <li><a href="index.php?opt=testing&view=faq_testing"> FAQs (Testing Services)</a></li>
                </ul>
                </li>

                <li><a href="#"><span>NQI Training & Membership </span></a>
                    <ul>
                        <li> <a href="index.php?opt=nqi&view=about">About NQI</a></li>
                        <li><a href="index.php?opt=nqi&view=functions">NQI Functions</a></li>
                        <li> <a href="index.php?opt=nqi&view=membership">Membership</a></li>
                        <li> <a href="index.php?opt=nqi&view=training">Training Services</a></li>
                         <li> <a href="http://www.kebs.org/index.php?opt=nqi&view=training_calender">Training Calendar</a></li>
                        <li> <a href="index.php?opt=nqi&view=awards">Kenya Quality Awards</a></li>
                        <li> <a href="index.php?opt=nqi&view=faqs">FAQs (NQI)</a></li>
                    </ul>
                </li>

                <li ><a href="#"><span>Certification Body</span></a>
                    <ul id="subnav">
                        <li><a href="index.php?opt=certification&view=aboutcb">About KEBS-CB</a></li>
                        <li><a href="index.php?opt=certification&view=schemes">Certification Schemes</a></li>
                        <li><a href="index.php?opt=certification&view=steps"> Certification Steps</a></li>
                        <li><a href="index.php?opt=certification&view=policies">Certification Policies </a></li>
                        <li><a href="index.php?opt=certification&view=certified_firms">Certified Firms</a></li>
                     <!--   <li><a href="index.php?opt=certification&view=statement">Statement of Impartiality    </a></li> -->
                        <li><a href="index.php?opt=certification&view=confidentiality">Auditor Confidentiality  </a></li>
                        <li><a href="index.php?opt=certification&view=feedback">Feedback, Complaints and Appeals    </a></li>                   
                        <li><a href="index.php?opt=certification&view=faqs">FAQ's (Certification)</a></li>
                    </ul>


<!--                    <li><a href="index.php?opt=downloads"><span>Downloads</span></a></li>                           		                                                        -->



                    </ul>
            </div>

        </div>
        <?
        include_once 'includes/configdb.php';
        //include_once 'includes/db_connect.php';
        include("includes/general.inc.php");
        ?>
                            
                            
                            